export const pageRoutes = {
  main: "/",
  login: "/login",
  register: "/register",
  myPage: "/mypage",
  myPageId: "/mypage/:id",
  editMyPage: "/editmypage",
  eventPage: "/eventpage",
  upCommingList: "/upcomminglist",
  upCommingPost: "/upcomminglist/:id",
  currentList: "/currentlist",
  currentPost: "/currentlist/:id",
  curatorList: "/curatorlist",
  curatorPost: "/curatorlist/:id",
  postList: "/postlist",
  postPost: "/postlist/:id",
  uploadExhibition: "/uploadexhibition",
  uploadCurator: "/uploadcurator",
  uploadPost: "/uploadpost",
};
