export const pageRoutes = {
  main: "/",
  login: "/login",
  register: "/register",
  myPage: "/mypage",
  editMyPage: "/editmypage",
  eventPage: "/eventpage",
  upCommingList: "/upcomminglist",
  upCommingPost: "/upcomminglist/:id",
  introduceList: "/introducelist",
  introducePost: "/introducelist/:id",
  curatorList: "/curatorlist",
  curatorPost: "/curatorlist/:id",
  postList: "/postlist",
  postPost: "/postlist/:id",
  uploadExhibition: "/uploadexhibition",
  uploadCurator: "/uploadcurator",
  uploadPost: "/uploadpost",
};
